export const data = [
    {
        key:1,
      name: 'Apple',
      category: 'Fruit',
      price: '$2.00',
      quantity: '100gr',
      image: require('./img/apple-01.jpg'),
    },
    {key:2,
      name: 'Banana',
      category: 'Fruit',
      price: '$3.00',
      quantity: '100gr',
      image: require('./img/bananas-01.jpg'),
    },
    {key:3,
      name: 'Spinach',
      category: 'Vegetable',
      price: '$1.00',
      quantity: '100gr',
      image: require('./img/spinach.png'),
    },
  
    {key:4,
      name: 'Tomato',
      category: 'Vegetable',
      price: '$2.00',
      quantity: '100gr',
      image: require('./img/tomato.jpg'),
    },
    {key:5,
      name: 'Beef',
      category: 'Meat',
      price: '$40.00',
      quantity: '1 kg',
      image: require('./img/meat.jpg'),
    },
    {key:6,
      name: 'Apple',
      category: 'Fruit',
      price: '$2.00',
      quantity: '100gr',
      image: require('./img/apple-01.jpg'),
    },
    {key:7,
      name: 'Banana',
      category: 'Fruit',
      price: '$3.00',
      quantity: '100gr',
      image: require('./img/bananas-01.jpg'),
    },
    {key:8,
      name: 'Spinach',
      category: 'Vegetable',
      price: '$1.00',
      quantity: '100gr',
      image: require('./img/spinach.png'),
    },
  
    {key:9,
      name: 'Tomato',
      category: 'Vegetable',
      price: '$2.00',
      quantity: '100gr',
      image: require('./img/tomato.jpg'),
    },
    {key:10,
      name: 'Beef',
      category: 'Meat',
      price: '$40.00',
      quantity: '1 kg',
      image: require('./img/meat.jpg'),
    },
    {key:11,
      name: 'Apple',
      category: 'Fruit',
      price: '$2.00',
      quantity: '100gr',
      image: require('./img/apple-01.jpg'),
    },
    {key:12,
      name: 'Banana',
      category: 'Fruit',
      price: '$3.00',
      quantity: '100gr',
      image: require('./img/bananas-01.jpg'),
    },
    {key:13,
      name: 'Spinach',
      category: 'Vegetable',
      price: '$1.00',
      quantity: '100gr',
      image: require('./img/spinach.png'),
    },
  
    {key:14,
      name: 'Tomato',
      category: 'Vegetable',
      price: '$2.00',
      quantity: '100gr',
      image: require('./img/tomato.jpg'),
    },
    {key:15,
      name: 'Beef',
      category: 'Meat',
      price: '$40.00',
      quantity: '1 kg',
      image: require('./img/meat.jpg'),
    },
  ];